// <auto-generated />
using System;
using Cinema.DAL.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Cinema.DAL.Migrations
{
    [DbContext(typeof(QuanLyRapPhimContext))]
    [Migration("20260710181806_AddMassTransitOutbox")]
    partial class AddMassTransitOutbox
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Cinema.DAL.Models.ChiTietDoAn", b =>
                {
                    b.Property<int>("MaHd")
                        .HasColumnType("int")
                        .HasColumnName("MaHD");

                    b.Property<int>("MaDoAn")
                        .HasColumnType("int");

                    b.Property<decimal?>("Gia")
                        .HasColumnType("money");

                    b.Property<int?>("SoLuong")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.HasKey("MaHd", "MaDoAn");

                    b.HasIndex(new[] { "MaDoAn" }, "IX_ChiTietDoAn_MaDoAn");

                    b.ToTable("ChiTietDoAn", (string)null);
                });

            modelBuilder.Entity("Cinema.DAL.Models.ChiTietHoaDon", b =>
                {
                    b.Property<int>("MaHd")
                        .HasColumnType("int")
                        .HasColumnName("MaHD");

                    b.Property<int>("MaGhe")
                        .HasColumnType("int");

                    b.Property<decimal?>("GiaVe")
                        .HasColumnType("money");

                    b.Property<int?>("MaLich")
                        .HasColumnType("int");

                    b.HasKey("MaHd", "MaGhe");

                    b.HasIndex("MaGhe");

                    b.HasIndex(new[] { "MaLich" }, "IX_ChiTietHoaDon_MaLich");

                    b.ToTable("ChiTietHoaDon", (string)null);
                });

            modelBuilder.Entity("Cinema.DAL.Models.DoAn", b =>
                {
                    b.Property<int>("MaDoAn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaDoAn"));

                    b.Property<decimal?>("Gia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("money")
                        .HasDefaultValue(0m);

                    b.Property<string>("Loai")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TenDoAn")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("MaDoAn");

                    b.ToTable("DoAn", (string)null);
                });

            modelBuilder.Entity("Cinema.DAL.Models.Ghe", b =>
                {
                    b.Property<int>("MaGhe")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaGhe"));

                    b.Property<string>("Hang")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<string>("LoaiGhe")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Thường");

                    b.Property<int?>("MaPhong")
                        .HasColumnType("int");

                    b.Property<int?>("SoGhe")
                        .HasColumnType("int");

                    b.HasKey("MaGhe");

                    b.HasIndex(new[] { "MaPhong" }, "IX_Ghe_MaPhong");

                    b.ToTable("Ghe", (string)null);
                });

            modelBuilder.Entity("Cinema.DAL.Models.HoaDon", b =>
                {
                    b.Property<int>("MaHd")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MaHD");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaHd"));

                    b.Property<int?>("MaKh")
                        .HasColumnType("int")
                        .HasColumnName("MaKH");

                    b.Property<int?>("MaNv")
                        .HasColumnType("int")
                        .HasColumnName("MaNV");

                    b.Property<DateTime?>("NgayDat")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<decimal?>("TongTien")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("money")
                        .HasDefaultValue(0m);

                    b.Property<string>("TrangThai")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Chờ thanh toán");

                    b.HasKey("MaHd");

                    b.HasIndex(new[] { "MaKh" }, "IX_HoaDon_MaKH");

                    b.HasIndex(new[] { "MaNv" }, "IX_HoaDon_MaNV");

                    b.ToTable("HoaDon", null, t =>
                        {
                            t.HasTrigger("trg_NganXoaHoaDonCoCTHD");
                        });

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);
                });

            modelBuilder.Entity("Cinema.DAL.Models.KhachHang", b =>
                {
                    b.Property<int>("MaKh")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MaKH");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaKh"));

                    b.Property<int?>("DiemTichLuy")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("HoTen")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MatKhau")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<DateOnly?>("NgaySinh")
                        .HasColumnType("date");

                    b.Property<string>("Sdt")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("SDT");

                    b.Property<string>("TaiKhoan")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("MaKh");

                    b.HasIndex(new[] { "TaiKhoan" }, "UQ_KhachHang_TaiKhoan")
                        .IsUnique();

                    b.ToTable("KhachHang", (string)null);
                });

            modelBuilder.Entity("Cinema.DAL.Models.KhuyenMai", b =>
                {
                    b.Property<int>("MaKm")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MaKM");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaKm"));

                    b.Property<string>("DieuKien")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateOnly?>("NgayBatDau")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("NgayKetThuc")
                        .HasColumnType("date");

                    b.Property<decimal?>("PhanTramGiam")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(5, 2)")
                        .HasDefaultValue(0m);

                    b.Property<string>("TenKm")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("TenKM");

                    b.HasKey("MaKm");

                    b.ToTable("KhuyenMai", (string)null);
                });

            modelBuilder.Entity("Cinema.DAL.Models.LichChieu", b =>
                {
                    b.Property<int>("MaLich")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaLich"));

                    b.Property<decimal?>("GiaVe")
                        .HasColumnType("money");

                    b.Property<TimeOnly?>("GioChieu")
                        .HasColumnType("time");

                    b.Property<int?>("MaPhim")
                        .HasColumnType("int");

                    b.Property<int?>("MaPhong")
                        .HasColumnType("int");

                    b.Property<DateOnly?>("NgayChieu")
                        .HasColumnType("date");

                    b.HasKey("MaLich");

                    b.HasIndex(new[] { "MaPhim" }, "IX_LichChieu_MaPhim");

                    b.HasIndex(new[] { "MaPhong" }, "IX_LichChieu_MaPhong");

                    b.ToTable("LichChieu", (string)null);
                });

            modelBuilder.Entity("Cinema.DAL.Models.NhanVien", b =>
                {
                    b.Property<int>("MaNv")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MaNV");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaNv"));

                    b.Property<string>("ChucVu")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("HoTen")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MatKhau")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("PhanQuyen")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("NhanVien");

                    b.Property<string>("TaiKhoan")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("MaNv");

                    b.HasIndex(new[] { "TaiKhoan" }, "UQ_NhanVien_TaiKhoan")
                        .IsUnique();

                    b.ToTable("NhanVien", (string)null);
                });

            modelBuilder.Entity("Cinema.DAL.Models.Phim", b =>
                {
                    b.Property<int>("MaPhim")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaPhim"));

                    b.Property<string>("DaoDien")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("NgayKhoiChieu")
                        .HasColumnType("datetime");

                    b.Property<string>("Poster")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenPhim")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("TheLoai")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("ThoiLuong")
                        .HasColumnType("int");

                    b.HasKey("MaPhim");

                    b.ToTable("Phim", (string)null);
                });

            modelBuilder.Entity("Cinema.DAL.Models.PhongChieu", b =>
                {
                    b.Property<int>("MaPhong")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaPhong"));

                    b.Property<string>("LoaiPhong")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("2D");

                    b.Property<int?>("SucChua")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("TenPhong")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("MaPhong");

                    b.ToTable("PhongChieu", (string)null);
                });

            modelBuilder.Entity("Cinema.DAL.Models.VwDoanhThuTheoPhim", b =>
                {
                    b.Property<int>("MaPhim")
                        .HasColumnType("int");

                    b.Property<int?>("SoLuongHoaDon")
                        .HasColumnType("int");

                    b.Property<string>("TenPhim")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("TongDoanhThu")
                        .HasColumnType("money");

                    b.ToTable((string)null);

                    b.ToView("vw_DoanhThuTheoPhim", (string)null);
                });

            modelBuilder.Entity("MassTransit.EntityFrameworkCoreIntegration.InboxState", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("Consumed")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("ConsumerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("Delivered")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ExpirationTime")
                        .HasColumnType("datetime2");

                    b.Property<long?>("LastSequenceNumber")
                        .HasColumnType("bigint");

                    b.Property<Guid>("LockId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("MessageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ReceiveCount")
                        .HasColumnType("int");

                    b.Property<DateTime>("Received")
                        .HasColumnType("datetime2");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("Id");

                    b.HasIndex("Delivered");

                    b.ToTable("InboxState");
                });

            modelBuilder.Entity("MassTransit.EntityFrameworkCoreIntegration.OutboxMessage", b =>
                {
                    b.Property<long>("SequenceNumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("SequenceNumber"));

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<Guid?>("ConversationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CorrelationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DestinationAddress")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime?>("EnqueueTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ExpirationTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("FaultAddress")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Headers")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("InboxConsumerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("InboxMessageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("InitiatorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("MessageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("MessageType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("OutboxId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Properties")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("RequestId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ResponseAddress")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime>("SentTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("SourceAddress")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("SequenceNumber");

                    b.HasIndex("EnqueueTime");

                    b.HasIndex("ExpirationTime");

                    b.HasIndex("OutboxId", "SequenceNumber")
                        .IsUnique()
                        .HasFilter("[OutboxId] IS NOT NULL");

                    b.HasIndex("InboxMessageId", "InboxConsumerId", "SequenceNumber")
                        .IsUnique()
                        .HasFilter("[InboxMessageId] IS NOT NULL AND [InboxConsumerId] IS NOT NULL");

                    b.ToTable("OutboxMessage");
                });

            modelBuilder.Entity("MassTransit.EntityFrameworkCoreIntegration.OutboxState", b =>
                {
                    b.Property<Guid>("OutboxId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Delivered")
                        .HasColumnType("datetime2");

                    b.Property<long?>("LastSequenceNumber")
                        .HasColumnType("bigint");

                    b.Property<Guid>("LockId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("OutboxId");

                    b.HasIndex("Created");

                    b.ToTable("OutboxState");
                });

            modelBuilder.Entity("Cinema.DAL.Models.ChiTietDoAn", b =>
                {
                    b.HasOne("Cinema.DAL.Models.DoAn", "MaDoAnNavigation")
                        .WithMany("ChiTietDoAns")
                        .HasForeignKey("MaDoAn")
                        .IsRequired()
                        .HasConstraintName("FK_CTDoAn_DoAn");

                    b.HasOne("Cinema.DAL.Models.HoaDon", "MaHdNavigation")
                        .WithMany("ChiTietDoAns")
                        .HasForeignKey("MaHd")
                        .IsRequired()
                        .HasConstraintName("FK_CTDoAn_HoaDon");

                    b.Navigation("MaDoAnNavigation");

                    b.Navigation("MaHdNavigation");
                });

            modelBuilder.Entity("Cinema.DAL.Models.ChiTietHoaDon", b =>
                {
                    b.HasOne("Cinema.DAL.Models.Ghe", "MaGheNavigation")
                        .WithMany("ChiTietHoaDons")
                        .HasForeignKey("MaGhe")
                        .IsRequired()
                        .HasConstraintName("FK_CTHD_Ghe");

                    b.HasOne("Cinema.DAL.Models.HoaDon", "MaHdNavigation")
                        .WithMany("ChiTietHoaDons")
                        .HasForeignKey("MaHd")
                        .IsRequired()
                        .HasConstraintName("FK_CTHD_HoaDon");

                    b.HasOne("Cinema.DAL.Models.LichChieu", "MaLichNavigation")
                        .WithMany("ChiTietHoaDons")
                        .HasForeignKey("MaLich")
                        .HasConstraintName("FK_CTHD_LichChieu");

                    b.Navigation("MaGheNavigation");

                    b.Navigation("MaHdNavigation");

                    b.Navigation("MaLichNavigation");
                });

            modelBuilder.Entity("Cinema.DAL.Models.Ghe", b =>
                {
                    b.HasOne("Cinema.DAL.Models.PhongChieu", "MaPhongNavigation")
                        .WithMany("Ghes")
                        .HasForeignKey("MaPhong")
                        .HasConstraintName("FK_Ghe_PhongChieu");

                    b.Navigation("MaPhongNavigation");
                });

            modelBuilder.Entity("Cinema.DAL.Models.HoaDon", b =>
                {
                    b.HasOne("Cinema.DAL.Models.KhachHang", "MaKhNavigation")
                        .WithMany("HoaDons")
                        .HasForeignKey("MaKh")
                        .HasConstraintName("FK_HoaDon_KhachHang");

                    b.HasOne("Cinema.DAL.Models.NhanVien", "MaNvNavigation")
                        .WithMany("HoaDons")
                        .HasForeignKey("MaNv")
                        .HasConstraintName("FK_HoaDon_NhanVien");

                    b.Navigation("MaKhNavigation");

                    b.Navigation("MaNvNavigation");
                });

            modelBuilder.Entity("Cinema.DAL.Models.LichChieu", b =>
                {
                    b.HasOne("Cinema.DAL.Models.Phim", "MaPhimNavigation")
                        .WithMany("LichChieus")
                        .HasForeignKey("MaPhim")
                        .HasConstraintName("FK_LichChieu_Phim");

                    b.HasOne("Cinema.DAL.Models.PhongChieu", "MaPhongNavigation")
                        .WithMany("LichChieus")
                        .HasForeignKey("MaPhong")
                        .HasConstraintName("FK_LichChieu_PhongChieu");

                    b.Navigation("MaPhimNavigation");

                    b.Navigation("MaPhongNavigation");
                });

            modelBuilder.Entity("MassTransit.EntityFrameworkCoreIntegration.OutboxMessage", b =>
                {
                    b.HasOne("MassTransit.EntityFrameworkCoreIntegration.OutboxState", null)
                        .WithMany()
                        .HasForeignKey("OutboxId");

                    b.HasOne("MassTransit.EntityFrameworkCoreIntegration.InboxState", null)
                        .WithMany()
                        .HasForeignKey("InboxMessageId", "InboxConsumerId")
                        .HasPrincipalKey("MessageId", "ConsumerId");
                });

            modelBuilder.Entity("Cinema.DAL.Models.DoAn", b =>
                {
                    b.Navigation("ChiTietDoAns");
                });

            modelBuilder.Entity("Cinema.DAL.Models.Ghe", b =>
                {
                    b.Navigation("ChiTietHoaDons");
                });

            modelBuilder.Entity("Cinema.DAL.Models.HoaDon", b =>
                {
                    b.Navigation("ChiTietDoAns");

                    b.Navigation("ChiTietHoaDons");
                });

            modelBuilder.Entity("Cinema.DAL.Models.KhachHang", b =>
                {
                    b.Navigation("HoaDons");
                });

            modelBuilder.Entity("Cinema.DAL.Models.LichChieu", b =>
                {
                    b.Navigation("ChiTietHoaDons");
                });

            modelBuilder.Entity("Cinema.DAL.Models.NhanVien", b =>
                {
                    b.Navigation("HoaDons");
                });

            modelBuilder.Entity("Cinema.DAL.Models.Phim", b =>
                {
                    b.Navigation("LichChieus");
                });

            modelBuilder.Entity("Cinema.DAL.Models.PhongChieu", b =>
                {
                    b.Navigation("Ghes");

                    b.Navigation("LichChieus");
                });
#pragma warning restore 612, 618
        }
    }
}
