// <auto-generated />
using System;
using Cinema.DAL.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Cinema.DAL.Migrations
{
    [DbContext(typeof(QuanLyRapPhimContext))]
    [Migration("20260415104231_1")]
    partial class _1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Cinema.DAL.Models.ChiTietDv", b =>
                {
                    b.Property<int>("MaHd")
                        .HasColumnType("int")
                        .HasColumnName("MaHD");

                    b.Property<int>("MaDv")
                        .HasColumnType("int")
                        .HasColumnName("MaDV");

                    b.Property<decimal?>("DonGiaBan")
                        .HasColumnType("money");

                    b.Property<int?>("SoLuong")
                        .HasColumnType("int");

                    b.HasKey("MaHd", "MaDv")
                        .HasName("PK__ChiTietD__4557FE856337680E");

                    b.HasIndex("MaDv");

                    b.ToTable("ChiTietDV", (string)null);
                });

            modelBuilder.Entity("Cinema.DAL.Models.DichVu", b =>
                {
                    b.Property<int>("MaDv")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MaDV");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaDv"));

                    b.Property<decimal?>("DonGia")
                        .HasColumnType("money");

                    b.Property<int?>("SoLuongTon")
                        .HasColumnType("int");

                    b.Property<string>("TenDv")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("TenDV");

                    b.HasKey("MaDv")
                        .HasName("PK__DichVu__27258657D6403FCF");

                    b.ToTable("DichVu", (string)null);
                });

            modelBuilder.Entity("Cinema.DAL.Models.Ghe", b =>
                {
                    b.Property<int>("MaGhe")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaGhe"));

                    b.Property<string>("LoaiGhe")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("MaPhong")
                        .HasColumnType("int");

                    b.Property<string>("TenGhe")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.HasKey("MaGhe")
                        .HasName("DF__Ghe__DaDat__3D5E1FD2");

                    b.HasIndex("MaPhong");

                    b.ToTable("Ghe", (string)null);
                });

            modelBuilder.Entity("Cinema.DAL.Models.HoaDon", b =>
                {
                    b.Property<int>("MaHd")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MaHD");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaHd"));

                    b.Property<int?>("MaNd")
                        .HasColumnType("int")
                        .HasColumnName("MaND");

                    b.Property<DateTime?>("NgayLap")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<decimal?>("TongTien")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("money")
                        .HasDefaultValue(0m);

                    b.HasKey("MaHd")
                        .HasName("PK__HoaDon__2725A6E0E68C72B0");

                    b.HasIndex("MaNd");

                    b.ToTable("HoaDon", null, t =>
                        {
                            t.HasTrigger("trg_NganXoaHoaDonCoVe");
                        });

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);
                });

            modelBuilder.Entity("Cinema.DAL.Models.LoaiPhim", b =>
                {
                    b.Property<int>("MaLoai")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaLoai"));

                    b.Property<string>("TenLoai")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("MaLoai")
                        .HasName("PK__LoaiPhim__730A57599BA3C329");

                    b.ToTable("LoaiPhim", (string)null);
                });

            modelBuilder.Entity("Cinema.DAL.Models.NguoiDung", b =>
                {
                    b.Property<int>("MaNd")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MaND");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaNd"));

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("HoTen")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool?>("IsAdmin")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("MatKhau")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("TaiKhoan")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("MaNd")
                        .HasName("PK__NguoiDun__2725D724C88B3203");

                    b.HasIndex(new[] { "TaiKhoan" }, "UQ__NguoiDun__D5B8C7F0B65F44B0")
                        .IsUnique();

                    b.ToTable("NguoiDung", (string)null);
                });

            modelBuilder.Entity("Cinema.DAL.Models.Phim", b =>
                {
                    b.Property<int>("MaPhim")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaPhim"));

                    b.Property<int?>("GioiHanTuoi")
                        .HasColumnType("int");

                    b.Property<string>("Hinh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("MaLoaiPhim")
                        .HasColumnType("int");

                    b.Property<DateTime?>("NgayKhoiChieu")
                        .HasColumnType("datetime");

                    b.Property<string>("TenPhim")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("ThoiLuong")
                        .HasColumnType("int");

                    b.HasKey("MaPhim")
                        .HasName("PK__Phim__4AC03DE3078CB066");

                    b.HasIndex("MaLoaiPhim");

                    b.ToTable("Phim", (string)null);
                });

            modelBuilder.Entity("Cinema.DAL.Models.Phong", b =>
                {
                    b.Property<int>("MaPhong")
                        .HasColumnType("int");

                    b.Property<int?>("SoLuongGhe")
                        .HasColumnType("int");

                    b.Property<string>("TenPhong")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("MaPhong")
                        .HasName("PK__Phong__20BD5E5B303B82C4");

                    b.ToTable("Phong", (string)null);
                });

            modelBuilder.Entity("Cinema.DAL.Models.SuatChieu", b =>
                {
                    b.Property<int>("MaSuat")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaSuat"));

                    b.Property<decimal?>("GiaVe")
                        .HasColumnType("money");

                    b.Property<TimeOnly?>("GioBatDau")
                        .HasColumnType("time");

                    b.Property<TimeOnly?>("GioKetThuc")
                        .HasColumnType("time");

                    b.Property<int?>("MaPhim")
                        .HasColumnType("int");

                    b.Property<int?>("MaPhong")
                        .HasColumnType("int");

                    b.Property<DateOnly?>("NgayChieu")
                        .HasColumnType("date");

                    b.Property<string>("TrangThai")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Sắp chiếu");

                    b.HasKey("MaSuat")
                        .HasName("PK__SuatChie__A69D0241CD876E94");

                    b.HasIndex("MaPhim");

                    b.HasIndex("MaPhong");

                    b.ToTable("SuatChieu", (string)null);
                });

            modelBuilder.Entity("Cinema.DAL.Models.Ve", b =>
                {
                    b.Property<int>("MaVe")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaVe"));

                    b.Property<decimal?>("GiaVe")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int?>("MaGhe")
                        .HasColumnType("int");

                    b.Property<int?>("MaHd")
                        .HasColumnType("int")
                        .HasColumnName("MaHD");

                    b.Property<int?>("MaSuat")
                        .HasColumnType("int");

                    b.HasKey("MaVe")
                        .HasName("PK__Ve__2725100F68C2289C");

                    b.HasIndex("MaGhe");

                    b.HasIndex("MaHd");

                    b.HasIndex(new[] { "MaSuat", "MaGhe" }, "UC_SuatChieu_Ghe")
                        .IsUnique()
                        .HasFilter("[MaSuat] IS NOT NULL AND [MaGhe] IS NOT NULL");

                    b.ToTable("Ve", (string)null);
                });

            modelBuilder.Entity("Cinema.DAL.Models.VwDoanhThuTheoPhim", b =>
                {
                    b.Property<int>("MaPhim")
                        .HasColumnType("int");

                    b.Property<int?>("SoLuongHoaDon")
                        .HasColumnType("int");

                    b.Property<string>("TenPhim")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("TongDoanhThu")
                        .HasColumnType("money");

                    b.ToTable((string)null);

                    b.ToView("vw_DoanhThuTheoPhim", (string)null);
                });

            modelBuilder.Entity("Cinema.DAL.Models.ChiTietDv", b =>
                {
                    b.HasOne("Cinema.DAL.Models.DichVu", "MaDvNavigation")
                        .WithMany("ChiTietDvs")
                        .HasForeignKey("MaDv")
                        .IsRequired()
                        .HasConstraintName("FK__ChiTietDV__MaDV__46E78A0C");

                    b.HasOne("Cinema.DAL.Models.HoaDon", "MaHdNavigation")
                        .WithMany("ChiTietDvs")
                        .HasForeignKey("MaHd")
                        .IsRequired()
                        .HasConstraintName("FK__ChiTietDV__MaHD__45F365D3");

                    b.Navigation("MaDvNavigation");

                    b.Navigation("MaHdNavigation");
                });

            modelBuilder.Entity("Cinema.DAL.Models.Ghe", b =>
                {
                    b.HasOne("Cinema.DAL.Models.Phong", "MaPhongNavigation")
                        .WithMany("Ghes")
                        .HasForeignKey("MaPhong")
                        .HasConstraintName("FK_Ghe_Phong");

                    b.Navigation("MaPhongNavigation");
                });

            modelBuilder.Entity("Cinema.DAL.Models.HoaDon", b =>
                {
                    b.HasOne("Cinema.DAL.Models.NguoiDung", "MaNdNavigation")
                        .WithMany("HoaDons")
                        .HasForeignKey("MaNd")
                        .HasConstraintName("FK_HoaDon_NguoiDung");

                    b.Navigation("MaNdNavigation");
                });

            modelBuilder.Entity("Cinema.DAL.Models.Phim", b =>
                {
                    b.HasOne("Cinema.DAL.Models.LoaiPhim", "MaLoaiPhimNavigation")
                        .WithMany("Phims")
                        .HasForeignKey("MaLoaiPhim")
                        .HasConstraintName("FK_Phim_LoaiPhim");

                    b.Navigation("MaLoaiPhimNavigation");
                });

            modelBuilder.Entity("Cinema.DAL.Models.SuatChieu", b =>
                {
                    b.HasOne("Cinema.DAL.Models.Phim", "MaPhimNavigation")
                        .WithMany("SuatChieus")
                        .HasForeignKey("MaPhim")
                        .HasConstraintName("FK__SuatChieu__MaPhi__398D8EEE");

                    b.HasOne("Cinema.DAL.Models.Phong", "MaPhongNavigation")
                        .WithMany("SuatChieus")
                        .HasForeignKey("MaPhong")
                        .HasConstraintName("FK_SuatChieu_Phong");

                    b.Navigation("MaPhimNavigation");

                    b.Navigation("MaPhongNavigation");
                });

            modelBuilder.Entity("Cinema.DAL.Models.Ve", b =>
                {
                    b.HasOne("Cinema.DAL.Models.Ghe", "MaGheNavigation")
                        .WithMany("Ves")
                        .HasForeignKey("MaGhe")
                        .HasConstraintName("FK_Ve_Ghe");

                    b.HasOne("Cinema.DAL.Models.HoaDon", "MaHdNavigation")
                        .WithMany("Ves")
                        .HasForeignKey("MaHd")
                        .HasConstraintName("FK__Ve__MaHD__4F7CD00D");

                    b.HasOne("Cinema.DAL.Models.SuatChieu", "MaSuatNavigation")
                        .WithMany("Ves")
                        .HasForeignKey("MaSuat")
                        .HasConstraintName("FK__Ve__MaSuat__4D94879B");

                    b.Navigation("MaGheNavigation");

                    b.Navigation("MaHdNavigation");

                    b.Navigation("MaSuatNavigation");
                });

            modelBuilder.Entity("Cinema.DAL.Models.DichVu", b =>
                {
                    b.Navigation("ChiTietDvs");
                });

            modelBuilder.Entity("Cinema.DAL.Models.Ghe", b =>
                {
                    b.Navigation("Ves");
                });

            modelBuilder.Entity("Cinema.DAL.Models.HoaDon", b =>
                {
                    b.Navigation("ChiTietDvs");

                    b.Navigation("Ves");
                });

            modelBuilder.Entity("Cinema.DAL.Models.LoaiPhim", b =>
                {
                    b.Navigation("Phims");
                });

            modelBuilder.Entity("Cinema.DAL.Models.NguoiDung", b =>
                {
                    b.Navigation("HoaDons");
                });

            modelBuilder.Entity("Cinema.DAL.Models.Phim", b =>
                {
                    b.Navigation("SuatChieus");
                });

            modelBuilder.Entity("Cinema.DAL.Models.Phong", b =>
                {
                    b.Navigation("Ghes");

                    b.Navigation("SuatChieus");
                });

            modelBuilder.Entity("Cinema.DAL.Models.SuatChieu", b =>
                {
                    b.Navigation("Ves");
                });
#pragma warning restore 612, 618
        }
    }
}
