// <auto-generated />
using System;
using Cinema.DAL.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Cinema.DAL.Migrations
{
    [DbContext(typeof(QuanLyRapPhimContext))]
    partial class QuanLyRapPhimContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Cinema.DAL.Models.ChiTietDoAn", b =>
                {
                    b.Property<int>("MaHD")
                        .HasColumnType("int");

                    b.Property<int>("MaDoAn")
                        .HasColumnType("int");

                    b.Property<decimal?>("Gia")
                        .HasColumnType("money");

                    b.Property<int?>("SoLuong")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.HasKey("MaHD", "MaDoAn")
                        .HasName("PK_ChiTietDoAn");

                    b.HasIndex("MaDoAn");

                    b.ToTable("ChiTietDoAn", (string)null);
                });

            modelBuilder.Entity("Cinema.DAL.Models.ChiTietHoaDon", b =>
                {
                    b.Property<int>("MaHD")
                        .HasColumnType("int");

                    b.Property<int>("MaGhe")
                        .HasColumnType("int");

                    b.Property<decimal?>("GiaVe")
                        .HasColumnType("money");

                    b.Property<int?>("MaLich")
                        .HasColumnType("int");

                    b.HasKey("MaHD", "MaGhe")
                        .HasName("PK_ChiTietHoaDon");

                    b.HasIndex("MaGhe");

                    b.HasIndex("MaLich");

                    b.ToTable("ChiTietHoaDon", (string)null);
                });

            modelBuilder.Entity("Cinema.DAL.Models.DoAn", b =>
                {
                    b.Property<int>("MaDoAn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaDoAn"));

                    b.Property<decimal?>("Gia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("money")
                        .HasDefaultValue(0m);

                    b.Property<string>("Loai")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TenDoAn")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("MaDoAn")
                        .HasName("PK_DoAn");

                    b.ToTable("DoAn", (string)null);
                });

            modelBuilder.Entity("Cinema.DAL.Models.Ghe", b =>
                {
                    b.Property<int>("MaGhe")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaGhe"));

                    b.Property<string>("Hang")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<string>("LoaiGhe")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Thường");

                    b.Property<int?>("MaPhong")
                        .HasColumnType("int");

                    b.Property<int?>("SoGhe")
                        .HasColumnType("int");

                    b.HasKey("MaGhe")
                        .HasName("PK_Ghe");

                    b.HasIndex("MaPhong");

                    b.ToTable("Ghe", (string)null);
                });

            modelBuilder.Entity("Cinema.DAL.Models.HoaDon", b =>
                {
                    b.Property<int>("MaHD")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaHD"));

                    b.Property<int?>("MaKH")
                        .HasColumnType("int");

                    b.Property<int?>("MaNV")
                        .HasColumnType("int");

                    b.Property<DateTime?>("NgayDat")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<decimal?>("TongTien")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("money")
                        .HasDefaultValue(0m);

                    b.Property<string>("TrangThai")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Chờ thanh toán");

                    b.HasKey("MaHD")
                        .HasName("PK_HoaDon");

                    b.HasIndex("MaKH");

                    b.HasIndex("MaNV");

                    b.ToTable("HoaDon", null, t =>
                        {
                            t.HasTrigger("trg_NganXoaHoaDonCoCTHD");
                        });

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);
                });

            modelBuilder.Entity("Cinema.DAL.Models.KhachHang", b =>
                {
                    b.Property<int>("MaKH")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaKH"));

                    b.Property<int?>("DiemTichLuy")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("HoTen")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MatKhau")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<DateOnly?>("NgaySinh")
                        .HasColumnType("date");

                    b.Property<string>("SDT")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("TaiKhoan")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("MaKH")
                        .HasName("PK_KhachHang");

                    b.HasIndex(new[] { "TaiKhoan" }, "UQ_KhachHang_TaiKhoan")
                        .IsUnique();

                    b.ToTable("KhachHang", (string)null);
                });

            modelBuilder.Entity("Cinema.DAL.Models.KhuyenMai", b =>
                {
                    b.Property<int>("MaKM")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaKM"));

                    b.Property<string>("DieuKien")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateOnly?>("NgayBatDau")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("NgayKetThuc")
                        .HasColumnType("date");

                    b.Property<decimal?>("PhanTramGiam")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(5,2)")
                        .HasDefaultValue(0m);

                    b.Property<string>("TenKM")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("MaKM")
                        .HasName("PK_KhuyenMai");

                    b.ToTable("KhuyenMai", (string)null);
                });

            modelBuilder.Entity("Cinema.DAL.Models.LichChieu", b =>
                {
                    b.Property<int>("MaLich")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaLich"));

                    b.Property<decimal?>("GiaVe")
                        .HasColumnType("money");

                    b.Property<TimeOnly?>("GioChieu")
                        .HasColumnType("time");

                    b.Property<int?>("MaPhim")
                        .HasColumnType("int");

                    b.Property<int?>("MaPhong")
                        .HasColumnType("int");

                    b.Property<DateOnly?>("NgayChieu")
                        .HasColumnType("date");

                    b.HasKey("MaLich")
                        .HasName("PK_LichChieu");

                    b.HasIndex("MaPhim");

                    b.HasIndex("MaPhong");

                    b.ToTable("LichChieu", (string)null);
                });

            modelBuilder.Entity("Cinema.DAL.Models.NhanVien", b =>
                {
                    b.Property<int>("MaNV")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaNV"));

                    b.Property<string>("ChucVu")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("HoTen")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MatKhau")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("PhanQuyen")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("NhanVien");

                    b.Property<string>("TaiKhoan")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("MaNV")
                        .HasName("PK_NhanVien");

                    b.HasIndex(new[] { "TaiKhoan" }, "UQ_NhanVien_TaiKhoan")
                        .IsUnique();

                    b.ToTable("NhanVien", (string)null);
                });

            modelBuilder.Entity("Cinema.DAL.Models.NhatKyHeThong", b =>
                {
                    b.Property<int>("MaNhatKy")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaNhatKy"));

                    b.Property<string>("DiaChi_IP")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("HanhDong")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MoTa")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("TaiKhoan")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("ThoiGian")
                        .HasColumnType("datetime2");

                    b.HasKey("MaNhatKy");

                    b.ToTable("NhatKyHeThong");
                });

            modelBuilder.Entity("Cinema.DAL.Models.Phim", b =>
                {
                    b.Property<int>("MaPhim")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaPhim"));

                    b.Property<string>("DaoDien")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("NgayKhoiChieu")
                        .HasColumnType("datetime");

                    b.Property<string>("Poster")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenPhim")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("TheLoai")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("ThoiLuong")
                        .HasColumnType("int");

                    b.HasKey("MaPhim")
                        .HasName("PK_Phim");

                    b.ToTable("Phim", (string)null);
                });

            modelBuilder.Entity("Cinema.DAL.Models.PhongChieu", b =>
                {
                    b.Property<int>("MaPhong")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaPhong"));

                    b.Property<string>("LoaiPhong")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("2D");

                    b.Property<int?>("SucChua")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("TenPhong")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("MaPhong")
                        .HasName("PK_PhongChieu");

                    b.ToTable("PhongChieu", (string)null);
                });

            modelBuilder.Entity("Cinema.DAL.Models.VwDoanhThuTheoPhim", b =>
                {
                    b.Property<int>("MaPhim")
                        .HasColumnType("int");

                    b.Property<int?>("SoLuongHoaDon")
                        .HasColumnType("int");

                    b.Property<string>("TenPhim")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("TongDoanhThu")
                        .HasColumnType("money");

                    b.ToTable((string)null);

                    b.ToView("vw_DoanhThuTheoPhim", (string)null);
                });

            modelBuilder.Entity("Cinema.DAL.Models.ChiTietDoAn", b =>
                {
                    b.HasOne("Cinema.DAL.Models.DoAn", "MaDoAnNavigation")
                        .WithMany("ChiTietDoAns")
                        .HasForeignKey("MaDoAn")
                        .IsRequired()
                        .HasConstraintName("FK_CTDoAn_DoAn");

                    b.HasOne("Cinema.DAL.Models.HoaDon", "MaHDNavigation")
                        .WithMany("ChiTietDoAns")
                        .HasForeignKey("MaHD")
                        .IsRequired()
                        .HasConstraintName("FK_CTDoAn_HoaDon");

                    b.Navigation("MaDoAnNavigation");

                    b.Navigation("MaHDNavigation");
                });

            modelBuilder.Entity("Cinema.DAL.Models.ChiTietHoaDon", b =>
                {
                    b.HasOne("Cinema.DAL.Models.Ghe", "MaGheNavigation")
                        .WithMany("ChiTietHoaDons")
                        .HasForeignKey("MaGhe")
                        .IsRequired()
                        .HasConstraintName("FK_CTHD_Ghe");

                    b.HasOne("Cinema.DAL.Models.HoaDon", "MaHDNavigation")
                        .WithMany("ChiTietHoaDons")
                        .HasForeignKey("MaHD")
                        .IsRequired()
                        .HasConstraintName("FK_CTHD_HoaDon");

                    b.HasOne("Cinema.DAL.Models.LichChieu", "MaLichNavigation")
                        .WithMany("ChiTietHoaDons")
                        .HasForeignKey("MaLich")
                        .HasConstraintName("FK_CTHD_LichChieu");

                    b.Navigation("MaGheNavigation");

                    b.Navigation("MaHDNavigation");

                    b.Navigation("MaLichNavigation");
                });

            modelBuilder.Entity("Cinema.DAL.Models.Ghe", b =>
                {
                    b.HasOne("Cinema.DAL.Models.PhongChieu", "MaPhongNavigation")
                        .WithMany("Ghes")
                        .HasForeignKey("MaPhong")
                        .HasConstraintName("FK_Ghe_PhongChieu");

                    b.Navigation("MaPhongNavigation");
                });

            modelBuilder.Entity("Cinema.DAL.Models.HoaDon", b =>
                {
                    b.HasOne("Cinema.DAL.Models.KhachHang", "MaKHNavigation")
                        .WithMany("HoaDons")
                        .HasForeignKey("MaKH")
                        .HasConstraintName("FK_HoaDon_KhachHang");

                    b.HasOne("Cinema.DAL.Models.NhanVien", "MaNVNavigation")
                        .WithMany("HoaDons")
                        .HasForeignKey("MaNV")
                        .HasConstraintName("FK_HoaDon_NhanVien");

                    b.Navigation("MaKHNavigation");

                    b.Navigation("MaNVNavigation");
                });

            modelBuilder.Entity("Cinema.DAL.Models.LichChieu", b =>
                {
                    b.HasOne("Cinema.DAL.Models.Phim", "MaPhimNavigation")
                        .WithMany("LichChieus")
                        .HasForeignKey("MaPhim")
                        .HasConstraintName("FK_LichChieu_Phim");

                    b.HasOne("Cinema.DAL.Models.PhongChieu", "MaPhongNavigation")
                        .WithMany("LichChieus")
                        .HasForeignKey("MaPhong")
                        .HasConstraintName("FK_LichChieu_PhongChieu");

                    b.Navigation("MaPhimNavigation");

                    b.Navigation("MaPhongNavigation");
                });

            modelBuilder.Entity("Cinema.DAL.Models.DoAn", b =>
                {
                    b.Navigation("ChiTietDoAns");
                });

            modelBuilder.Entity("Cinema.DAL.Models.Ghe", b =>
                {
                    b.Navigation("ChiTietHoaDons");
                });

            modelBuilder.Entity("Cinema.DAL.Models.HoaDon", b =>
                {
                    b.Navigation("ChiTietDoAns");

                    b.Navigation("ChiTietHoaDons");
                });

            modelBuilder.Entity("Cinema.DAL.Models.KhachHang", b =>
                {
                    b.Navigation("HoaDons");
                });

            modelBuilder.Entity("Cinema.DAL.Models.LichChieu", b =>
                {
                    b.Navigation("ChiTietHoaDons");
                });

            modelBuilder.Entity("Cinema.DAL.Models.NhanVien", b =>
                {
                    b.Navigation("HoaDons");
                });

            modelBuilder.Entity("Cinema.DAL.Models.Phim", b =>
                {
                    b.Navigation("LichChieus");
                });

            modelBuilder.Entity("Cinema.DAL.Models.PhongChieu", b =>
                {
                    b.Navigation("Ghes");

                    b.Navigation("LichChieus");
                });
#pragma warning restore 612, 618
        }
    }
}
